OrdererOrgs:
  - Name: Orderer
    Domain: orgorderer1
    Specs:
      - Hostname: orderer0

PeerOrgs:
  - Name: Org1
    Domain: org1
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
