---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka-0
  labels:
    app: kafka
    podindex: "0"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: "/data/kafka/datadir-kafka-0"
    server: 172.31.21.208
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka-1
  labels:
    app: kafka
    podindex: "1"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: "/data/kafka/datadir-kafka-1"
    server: 172.31.21.208
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka-2
  labels:
    app: kafka
    podindex: "2"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: "/data/kafka/datadir-kafka-2"
    server: 172.31.21.208
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-kafka-3
  labels:
    app: kafka
    podindex: "3"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: "/data/kafka/datadir-kafka-3"
    server: 172.31.21.208
