---
apiVersion: v1
kind: Namespace
metadata:
    name: $org

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $pvName
  labels:
    app: $pvName
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: $path
    server: 192.168.1.100

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: $org
 name: $pvName
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi
 selector:
   matchLabels:
     app: $pvName

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $pvDataName
  labels:
    app: $pvDataName
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: $datapath
    server: 192.168.1.100

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: $org
 name: $pvDataName
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Gi
 selector:
   matchLabels:
     app: $pvDataName
